"""ADDS THE AUTHOR COLUMN IN THE BLOGS TABLE

Revision ID: f863fc5ea1b4
Revises: a0e340a9a3e3
Create Date: 2021-11-13 10:49:32.708518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f863fc5ea1b4'
down_revision = 'a0e340a9a3e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('author', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'author')
    # ### end Alembic commands ###
